service: nestjs-typescript-challenge

frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-offline


provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6
  stage: dev
  region: us-east-2
  environment: 
    PORT: ${self:custom.supersecret.PORT}
    JWT_SECRET: ${self:custom.supersecret.JWT_SECRET}
    DB_HOST: ${self:custom.supersecret.DB_HOST}
    DB_PORT: ${self:custom.supersecret.DB_PORT}
    DB_USER: ${self:custom.supersecret.DB_USER}
    DB_PASS: ${self:custom.supersecret.DB_PASS}
    DB_DATABASE: ${self:custom.supersecret.DB_DATABASE}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}

custom:
#  secrets: ${file(./config/${self:provider.stage}.json)} # reference the secrets.json file
  supersecret: ${ssm:/aws/reference/secretsmanager/sales}
  stage: ${opt:stage, 'dev'}
  optimize:
    external: ['swagger-ui-dist']